export const GET_LATEST_RECIPE_PENDING = "GET_LATEST_RECIPE_PENDING";
export const GET_LATEST_RECIPE_SUCCESS = "GET_LATEST_RECIPE_SUCCESS";
export const GET_LATEST_RECIPE_FAILED = "GET_LATEST_RECIPE_FAILED";
