export const GET_LATEST_RECIPE_PENDING = "GET_LATEST_RECIPE_PENDING";
export const GET_LATEST_RECIPE_SUCCESS = "GET_LATEST_RECIPE_SUCCESS";
export const GET_LATEST_RECIPE_FAILED = "GET_LATEST_RECIPE_FAILED";

export const GET_LIST_RECIPE_PENDING = "GET_LIST_RECIPE_PENDING";
export const GET_LIST_RECIPE_SUCCESS = "GET_LIST_RECIPE_SUCCESS";
export const GET_LIST_RECIPE_FAILED = "GET_LIST_RECIPE_FAILED";

export const GET_DETAIL_RECIPE_PENDING = "GET_DETAIL_RECIPE_PENDING";
export const GET_DETAIL_RECIPE_SUCCESS = "GET_DETAIL_RECIPE_SUCCESS";
export const GET_DETAIL_RECIPE_FAILED = "GET_DETAIL_RECIPE_FAILED";

export const GET_DETAIL_USER_PENDING = "GET_DETAIL_USER_PENDING";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_FAILED = "GET_DETAIL_USER_FAILED";
